-- =====================================================================
-- UMI-USB Tests
-- =====================================================================

local test_dir = os.scriptdir()
local umiusb_dir = path.directory(test_dir)
local lib_dir = path.directory(umiusb_dir)
local root_dir = path.directory(lib_dir)

-- =====================================================================
-- Host unit tests
-- =====================================================================

target("test_usb_descriptor")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_descriptor.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()

target("test_usb_feedback")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_feedback.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()

target("test_usb_gain")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_gain.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()

target("test_usb_midi_class")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_midi_class.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()

target("test_usb_audio_class")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_audio_class.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()

target("test_usb_device")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_device.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()

target("test_usb_composite")
    add_rules("host.test")
    set_default(true)
    add_deps("umi.usb")
    add_files(path.join(test_dir, "test_composite.cc"))
    add_includedirs(path.join(root_dir, "tests"))
    add_includedirs(path.join(umiusb_dir, "include"))
    add_includedirs(path.join(umiusb_dir, "test"))
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()
