#!/usr/bin/env python3
"""
keygen.py - Generate Ed25519 key pair for UMI application signing

Usage:
    python3 keygen.py --out keys/

Output files:
    keys/private.key  - 32-byte private key seed (KEEP SECRET!)
    keys/public.key   - 32-byte public key
    keys/public_key.hh - C++ header file with public key

Requirements:
    pip install pynacl

Security notes:
    - Keep private.key SECRET and secure
    - Never commit private keys to version control
    - Use different key pairs for development and production
    - Back up your private key securely
"""

import argparse
import sys
from pathlib import Path

try:
    from nacl.signing import SigningKey
except ImportError:
    print("Error: PyNaCl not installed. Run: pip install pynacl", file=sys.stderr)
    sys.exit(1)


def generate_cpp_header(public_key: bytes, name: str = "RELEASE") -> str:
    """Generate C++ header file with public key."""
    hex_bytes = ', '.join(f'0x{b:02x}' for b in public_key)

    # Format in rows of 8 bytes
    rows = []
    for i in range(0, len(public_key), 8):
        row_bytes = public_key[i:i+8]
        row_hex = ', '.join(f'0x{b:02x}' for b in row_bytes)
        rows.append(f'    {row_hex},')

    formatted_bytes = '\n'.join(rows)

    return f'''// SPDX-License-Identifier: MIT
// Ed25519 Public Key for {name} Build
// Generated by tools/keygen.py
//
// IMPORTANT: This file is auto-generated. Do not edit manually.
// To regenerate: python3 tools/keygen.py --out keys/

#pragma once

#include <cstdint>

namespace umi::crypto {{

/// {name} build public key (32 bytes)
inline constexpr uint8_t {name}_PUBLIC_KEY[32] = {{
{formatted_bytes}
}};

}} // namespace umi::crypto
'''


def main():
    parser = argparse.ArgumentParser(
        description='Generate Ed25519 key pair for UMI application signing',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('--out', required=True, help='Output directory for key files')
    parser.add_argument('--name', default='RELEASE',
                        help='Name prefix for C++ constant (default: RELEASE)')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite existing files')

    args = parser.parse_args()

    # Create output directory
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Check for existing files
    private_path = out_dir / 'private.key'
    public_path = out_dir / 'public.key'
    header_path = out_dir / 'public_key.hh'

    if not args.force:
        existing = []
        for p in [private_path, public_path, header_path]:
            if p.exists():
                existing.append(str(p))
        if existing:
            print("Error: Files already exist (use --force to overwrite):",
                  file=sys.stderr)
            for p in existing:
                print(f"  {p}", file=sys.stderr)
            return 1

    # Generate key pair
    signing_key = SigningKey.generate()
    verify_key = signing_key.verify_key

    private_bytes = bytes(signing_key)  # 32-byte seed
    public_bytes = bytes(verify_key)    # 32-byte public key

    # Write private key
    private_path.write_bytes(private_bytes)
    print(f"Private key: {private_path}")

    # Write public key
    public_path.write_bytes(public_bytes)
    print(f"Public key:  {public_path}")

    # Write C++ header
    cpp_header = generate_cpp_header(public_bytes, args.name)
    header_path.write_text(cpp_header)
    print(f"C++ header:  {header_path}")

    # Print public key for reference
    print(f"\nPublic key (hex):")
    hex_str = public_bytes.hex()
    for i in range(0, len(hex_str), 32):
        print(f"  {hex_str[i:i+32]}")

    print(f"\nSECURITY WARNING:")
    print(f"  Keep {private_path} SECRET and secure!")
    print(f"  Never commit private keys to version control.")
    print(f"  Add to .gitignore: {out_dir}/*.key")

    return 0


if __name__ == '__main__':
    sys.exit(main())
